### ISSUE TITLE
提示地址有误

### ISSUE THREAD

**Issue by Yeeewz** [krapnikkk/JDCouponAssistant#4]
https://coupon.m.jd.com/coupons/show.action?key=b7dd4f29ea7748038310b5390e4fe5a2&roleId=27046553&time=1578041001232
在控制台运行bundle.js 脚本 填写这个地址这个地址，提示页面地址暂未被扩展。这种是哪里出的问题啊

**Comment by krapnikkk** [comment]
这种类型的地址已扩展了的，请等待页面加载完成后在运行脚本

**Comment by Yeeewz** [comment]
不是直接在控制台运行bundle.js 文件吗
