### ISSUE TITLE
使用

### ISSUE THREAD

**Issue by Yeeewz** [krapnikkk/JDCouponAssistant#5]
新手一枚，还是没弄明白你是怎么运行的

**Comment by krapnikkk** [comment]
点击插件中的QQ，直接联系我

**Comment by Yeeewz** [comment]
试过了，加不了你qq




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            叶威振
                            
                            
                                
                                    邮箱：yeeewz@gmail.com
                                
                        
                    
                
            
        
    


签名由 网易邮箱大师 定制


在2020年01月06日 20:55，krapnikkk 写道： Closed #5.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/krapnikkk/JDCouponAssistant/issues/5?email_source=notifications\u0026email_token=AIUE6CETZY7LP3XM5FKCNHLQ4MS4RA5CNFSM4KCVVRGKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOVZFFJPI#event-2924106941",
"url": "https://github.com/krapnikkk/JDCouponAssistant/issues/5?email_source=notifications\u0026email_token=AIUE6CETZY7LP3XM5FKCNHLQ4MS4RA5CNFSM4KCVVRGKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOVZFFJPI#event-2924106941",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
