### ISSUE TITLE
十二生肖的脚本也很期待

### ISSUE THREAD

**Issue by Tomatoro** [krapnikkk/JDCouponAssistant#7]

**Comment by krapnikkk** [comment]
已经添加了呀，又有新活动了？

**Comment by Tomatoro** [comment]
是一键完成任务里面吗? 需要切换到十二生肖的页面是吗?

**Comment by Tomatoro** [comment]
哈哈哈 看到了,感谢大佬!

**Comment by krapnikkk** [comment]
需要切换到对应的活动页面使用脚本，或者可以点击插件的下载视频教程查看如何使用




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Tomatoro"<notifications@github.com&gt;; 
发送时间: 2020年1月13日(星期一) 中午11:38
收件人: "krapnikkk/JDCouponAssistant"<JDCouponAssistant@noreply.github.com&gt;; 
抄送: "krapnik"<krapnik@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [krapnikkk/JDCouponAssistant] 十二生肖的脚本也很期待 (#7)




是一键完成任务里面吗? 需要切换到十二生肖的页面是吗?
